#include <ntddk.h>
#include "i2cctrl_dump.h"
#include "i2cctrl_hw.h"
#include "i2cctrl_ext.h"
#include "i2cctrl_etw.h"
#include "i2cctrl_etw.tmh"   /* auto-generated by WPP */

/* Global snapshot buffer (NonPaged) */
PI2CCTRL_DUMP_SNAPSHOT gSnap = NULL;



/* ---------- Allocate nonpaged snapshot buffer (genericized, XP/2003-safe) ----------
 * Prepares snapshot structure for abstract bus context capture.
 */
VOID
I2cCtrl_AllocSnapshotBuffer(VOID)
{
    PI2CCTRL_DUMP_SNAPSHOT p;

    /* Must be PASSIVE_LEVEL for pool operations */
    if (KeGetCurrentIrql() != PASSIVE_LEVEL) {
        TraceEvents(TRACE_LEVEL_WARNING, TRACE_FLAG_SNAPSHOT,
                    "AllocSnapshotBuffer: wrong IRQL=%lu", (ULONG)KeGetCurrentIrql());
        return;
    }

    if (gSnap != NULL) {
        return;
    }

    p = (PI2CCTRL_DUMP_SNAPSHOT)ExAllocatePoolWithTag(
            NonPagedPool,
            sizeof(I2CCTRL_DUMP_SNAPSHOT),
            I2CCTRL_TAG_DUMP);
    if (p == NULL) {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_FLAG_SNAPSHOT,
                    "AllocSnapshotBuffer: allocation failed");
        return;
    }

    RtlZeroMemory(p, sizeof(*p));

    /* Initialize snapshot header */
    p->Version      = I2CCTRL_DUMP_SNAPSHOT_VER;
    p->BusAddress   = 0U;
    p->BusSpeedHz   = 0U;
    p->TimingHighNs = 0U;
    p->TimingLowNs  = 0U;
    p->SpeedMode    = I2cSpeedFast;          /* safe default */
    p->CurrentState = PowerDeviceUnspecified;
    p->LastReason   = 0U;

    gSnap = p;

    TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_FLAG_SNAPSHOT,
                "AllocSnapshotBuffer: allocated snapshot buffer at %p (ver=%lu)",
                gSnap, p->Version);
}

/* ---------- Initialize dump subsystem (genericized) ----------
 * Prepares snapshot buffer for abstract bus context capture.
 */
VOID
I2cCtrl_DumpInit(
    PI2CCTRL_FDO dx
    )
{
    UNREFERENCED_PARAMETER(dx);

    /* Allocate or reset snapshot buffer */
    I2cCtrl_AllocSnapshotBuffer();

    if (gSnap != NULL) {
        gSnap->Version          = I2CCTRL_DUMP_SNAPSHOT_VER;
        gSnap->BusAddress       = 0U;
        gSnap->BusSpeedHz       = 0U;
        gSnap->TimingHighNs     = 0U;
        gSnap->TimingLowNs      = 0U;
        gSnap->SpeedMode        = I2cSpeedFast; /* safe default */
        gSnap->CurrentState     = PowerDeviceUnspecified;
        gSnap->LastReason       = 0U;
    }

    TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_FLAG_SNAPSHOT,
                "DumpInit complete (gSnap=%p, version=%lu)",
                gSnap,
                (gSnap != NULL) ? gSnap->Version : 0U);
}


/* ---------- Safe snapshot helper (genericized, enum-based) ----------
 * Returns abstract bus context instead of raw MMIO registers.
 * XP-safe: tolerates any IRQL, avoids unsafe MMIO access.
 */

__inline ULONG
I2cCtrl_ReadRegSnapshot(
    PI2CCTRL_FDO          dx,
    I2CCTRL_SNAPSHOT_FIELD fieldId
    )
{
    if (dx == NULL) {
        return 0U;
    }

    switch (fieldId) {
    case I2cSnapshot_BusAddress:
        return dx->SavedBusAddress;

    case I2cSnapshot_BusSpeedHz:
        return dx->SavedBusSpeed;

    case I2cSnapshot_TimingHighNs:
        return dx->SavedTimingHighNs;

    case I2cSnapshot_TimingLowNs:
        return dx->SavedTimingLowNs;

    case I2cSnapshot_PowerState:
        return (ULONG)dx->CurrentDevicePowerState;

    case I2cSnapshot_SpeedMode:
        return (ULONG)dx->SpeedMode;

    default:
        TraceEvents(TRACE_LEVEL_WARNING, TRACE_FLAG_SNAPSHOT,
                    "ReadRegSnapshot: unknown fieldId=%lu", (ULONG)fieldId);
        return 0U;
    }
}


/* ---------- Capture controller state into snapshot (enum-based, genericized) ----------
 * XP-safe: tolerates any IRQL, avoids unsafe MMIO access.
 */
VOID
I2cCtrl_CaptureSnapshot(
    PI2CCTRL_FDO dx,
    NTSTATUS     reason
    )
{
    LARGE_INTEGER now;
    KIRQL curIrql;

    if (gSnap == NULL) {
        return;
    }

    curIrql = KeGetCurrentIrql();
    KeQuerySystemTime(&now);

    gSnap->Version    = I2CCTRL_DUMP_SNAPSHOT_VER;
    gSnap->SystemTime = now;
    gSnap->Irql       = curIrql;
    gSnap->Dx         = dx;
    gSnap->LastReason = (ULONG)reason;

    /* If IRQL is too high, skip snapshot to avoid unsafe access */
    if (dx == NULL || curIrql > DISPATCH_LEVEL) {
        TraceEvents(TRACE_LEVEL_WARNING, TRACE_FLAG_SNAPSHOT,
                    "CaptureSnapshot: skipping context capture (IRQL=%lu, dx=%p)",
                    (ULONG)curIrql, dx);
        return;
    }

    /* Capture abstract bus context using safe helper */
    gSnap->BusAddress   = I2cCtrl_ReadRegSnapshot(dx, I2cSnapshot_BusAddress);
    gSnap->BusSpeedHz   = I2cCtrl_ReadRegSnapshot(dx, I2cSnapshot_BusSpeedHz);
    gSnap->TimingHighNs = I2cCtrl_ReadRegSnapshot(dx, I2cSnapshot_TimingHighNs);
    gSnap->TimingLowNs  = I2cCtrl_ReadRegSnapshot(dx, I2cSnapshot_TimingLowNs);
    gSnap->SpeedMode    = I2cCtrl_ReadRegSnapshot(dx, I2cSnapshot_SpeedMode);
    gSnap->CurrentState = I2cCtrl_ReadRegSnapshot(dx, I2cSnapshot_PowerState);

    /* Optionally refine timing if MMIO is mapped and IRQL safe */
    if (dx->Mmio != NULL) {
        gSnap->TimingHighNs = I2cCtrl_QueryTimingHigh(dx);
        gSnap->TimingLowNs  = I2cCtrl_QueryTimingLow(dx);
    }
}

/* ---------- Force crash with snapshot (genericized) ----------
 * XP-safe: uses KeBugCheckEx, tolerates any IRQL.
 */
VOID
I2cCtrl_ForceCrash(
    PI2CCTRL_FDO dx,
    NTSTATUS     reason
    )
{
    SIZE_T snapSize;

    TraceEvents(TRACE_LEVEL_ERROR, TRACE_FLAG_SNAPSHOT,
                "ForceCrash invoked, reason=0x%08X", reason);

    /* Best-effort snapshot capture; no paging or blocking */
    I2cCtrl_CaptureSnapshot(dx, reason);

    snapSize = (gSnap != NULL) ? sizeof(*gSnap) : 0;

    /* KeBugCheckEx is allowed at any IRQL; provide snapshot pointer for WinDBG */
    KeBugCheckEx(
        I2CCTRL_BUGCHECK_CODE,
        (ULONG_PTR)gSnap,       /* pointer to abstract snapshot */
        (ULONG_PTR)snapSize,    /* size of snapshot structure */
        (ULONG_PTR)reason,      /* reason code */
        (ULONG_PTR)((dx != NULL) ? dx->SavedBusSpeed : 0U) /* include bus speed for context */
    );
}

/* ---------- Crash on timeout/error (genericized) ----------
 * Explicit bugcheck with snapshot of abstract bus context.
 */
VOID
I2cCtrl_DumpOnTimeout(
    PI2CCTRL_FDO dx,
    NTSTATUS     reason
    )
{
    TraceEvents(TRACE_LEVEL_WARNING, TRACE_FLAG_SNAPSHOT,
                "Timeout detected (reason=0x%08X, busAddr=0x%X, speed=%luHz)",
                reason,
                (dx != NULL) ? dx->SavedBusAddress : 0U,
                (dx != NULL) ? dx->SavedBusSpeed   : 0U);

    /* Force crash with abstract snapshot */
    I2cCtrl_ForceCrash(dx, reason);
}


/* ---------- IOCTL handler to force a dump (genericized) ----------
 * WinDDK-safe: completes IRP before bugcheck to avoid dangling requests.
 */
NTSTATUS
I2cCtrl_HandleDumpIoctl(
    PI2CCTRL_FDO       dx,
    PIRP               Irp,
    PIO_STACK_LOCATION isl
    )
{
    UNREFERENCED_PARAMETER(isl);

    /* Complete the IRP first to avoid dangling requests in crash dumps */
    if (Irp != NULL) {
        Irp->IoStatus.Status      = STATUS_SUCCESS;
        Irp->IoStatus.Information = 0;
        IoCompleteRequest(Irp, IO_NO_INCREMENT);
    }

    TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_FLAG_IOCTL,
                "IOCTL_I2C_FORCE_CRASH received (busAddr=0x%X, speed=%luHz)",
                (dx != NULL) ? dx->SavedBusAddress : 0U,
                (dx != NULL) ? dx->SavedBusSpeed   : 0U);

    /* Trigger bugcheck after IRP completion with abstract snapshot */
    I2cCtrl_ForceCrash(dx, STATUS_UNSUCCESSFUL);

    /* Not reached */
    return STATUS_SUCCESS;
}
