MUI_386_OBJECTS= \
    $(_OBJ_DIR)\i386\i2chid_version.res

386_OBJECTS= \
    $(_OBJ_DIR)\i386\i2chid_version.res \
    $(_OBJ_DIR)\i386\i2chid.obj \
    $(_OBJ_DIR)\i386\i2chid_guids.obj \
    $(_OBJ_DIR)\i386\i2chid_acpi.obj \
    $(_OBJ_DIR)\i386\i2chid_hid.obj \
    $(_OBJ_DIR)\i386\i2chid_power.obj \
    $(_OBJ_DIR)\i386\i2chid_hw_shim.obj \
    $(_OBJ_DIR)\i386\i2chid_spbcx.obj \
    $(_OBJ_DIR)\i386\i2chid_pt.obj \
    $(_OBJ_DIR)\i386\i2chid_i2cctrl.obj \
    $(_OBJ_DIR)\i386\i2chid_dpi.obj

MUI_IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\i2chid_version.res

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\i2chid_version.res \
    $(_OBJ_DIR)\ia64\i2chid.obj \
    $(_OBJ_DIR)\ia64\i2chid_guids.obj \
    $(_OBJ_DIR)\ia64\i2chid_acpi.obj \
    $(_OBJ_DIR)\ia64\i2chid_hid.obj \
    $(_OBJ_DIR)\ia64\i2chid_power.obj \
    $(_OBJ_DIR)\ia64\i2chid_hw_shim.obj \
    $(_OBJ_DIR)\ia64\i2chid_spbcx.obj \
    $(_OBJ_DIR)\ia64\i2chid_pt.obj \
    $(_OBJ_DIR)\ia64\i2chid_i2cctrl.obj \
    $(_OBJ_DIR)\ia64\i2chid_dpi.obj

MUI_AMD64_OBJECTS= \
    $(_OBJ_DIR)\amd64\i2chid_version.res

AMD64_OBJECTS= \
    $(_OBJ_DIR)\amd64\i2chid_version.res \
    $(_OBJ_DIR)\amd64\i2chid.obj \
    $(_OBJ_DIR)\amd64\i2chid_guids.obj \
    $(_OBJ_DIR)\amd64\i2chid_acpi.obj \
    $(_OBJ_DIR)\amd64\i2chid_hid.obj \
    $(_OBJ_DIR)\amd64\i2chid_power.obj \
    $(_OBJ_DIR)\amd64\i2chid_hw_shim.obj \
    $(_OBJ_DIR)\amd64\i2chid_spbcx.obj \
    $(_OBJ_DIR)\amd64\i2chid_pt.obj \
    $(_OBJ_DIR)\amd64\i2chid_i2cctrl.obj \
    $(_OBJ_DIR)\amd64\i2chid_dpi.obj

MUI_ARM_OBJECTS= \
    $(_OBJ_DIR)\arm\i2chid_version.res

ARM_OBJECTS= \
    $(_OBJ_DIR)\arm\i2chid_version.res \
    $(_OBJ_DIR)\arm\i2chid.obj \
    $(_OBJ_DIR)\arm\i2chid_guids.obj \
    $(_OBJ_DIR)\arm\i2chid_acpi.obj \
    $(_OBJ_DIR)\arm\i2chid_hid.obj \
    $(_OBJ_DIR)\arm\i2chid_power.obj \
    $(_OBJ_DIR)\arm\i2chid_hw_shim.obj \
    $(_OBJ_DIR)\arm\i2chid_spbcx.obj \
    $(_OBJ_DIR)\arm\i2chid_pt.obj \
    $(_OBJ_DIR)\arm\i2chid_i2cctrl.obj \
    $(_OBJ_DIR)\arm\i2chid_dpi.obj

