

AMD64_OBJECTS=\
 $(OBJ_PATH)\$O\i2cctrl.obj \
 $(OBJ_PATH)\$O\i2cctrl_log.obj \
 $(OBJ_PATH)\$O\i2cctrl_zw.obj \
 $(OBJ_PATH)\$O\i2cctrl_backport.obj \
 $(OBJ_PATH)\$O\i2cctrl_bsod.obj \
 $(OBJ_PATH)\$O\i2cctrl_detect.obj \
 $(OBJ_PATH)\$O\i2cctrl_extra.obj \
 $(OBJ_PATH)\$O\i2cctrl_dump.obj \
 $(OBJ_PATH)\$O\i2cctrl_etw.obj \
 $(OBJ_PATH)\$O\i2cctrl_fdo.obj \
 $(OBJ_PATH)\$O\i2cctrl_guid.obj \
 $(OBJ_PATH)\$O\i2cctrl_i2c.obj \
 $(OBJ_PATH)\$O\i2cctrl_isr.obj \
 $(OBJ_PATH)\$O\i2cctrl_pdo.obj \
 $(OBJ_PATH)\$O\i2cctrl_queue.obj \
 $(OBJ_PATH)\$O\i2cctrl_smbus.obj \
 $(OBJ_PATH)\$O\i2cctrl_spbcx.obj \
 $(OBJ_PATH)\$O\i2cctrl_acpiex.obj \
 $(OBJ_PATH)\$O\i2cctrl_i2chid.obj \
 $(OBJ_PATH)\$O\i2cctrl_dpi.obj \
 $(OBJ_PATH)\$O\i2cctrl_wdm_compat.obj \
 $(OBJ_PATH)\$O\i2cctrl_hal_ops.obj \
 $(OBJ_PATH)\$O\i2cctrl_hal_dw.obj \
 $(OBJ_PATH)\$O\i2cctrl_hal_acpi.obj \
 $(OBJ_PATH)\$O\i2cctrl_hal_realtek.obj \
 $(OBJ_PATH)\$O\i2cctrl_hal_qualcomm.obj \
 $(OBJ_PATH)\$O\i2cctrl_hal_nvidia.obj \
 $(OBJ_PATH)\$O\i2cctrl_hal_apple.obj \
 $(OBJ_PATH)\$O\i2cctrl_hal_broadcom.obj \
 $(OBJ_PATH)\$O\i2cctrl_hal_mediatek.obj \
 $(OBJ_PATH)\$O\i2cctrl_hal_samsung.obj \
 $(OBJ_PATH)\$O\i2cctrl_hal_via.obj \
 $(OBJ_PATH)\$O\i2cctrl_hal_sifive.obj \
 $(OBJ_PATH)\$O\i2cctrl_hal_rockchip.obj \
 $(OBJ_PATH)\$O\i2cctrl_hal_amd_vendor.obj \
 $(OBJ_PATH)\$O\i2cctrl_hal_intel_vendor.obj \
 $(OBJ_PATH)\$O\i2cctrl_hal_soft.obj \


_RES_FILE=$(OBJ_PATH)\$O\i2cctrl_version.res



# lowercased
BASEDIR=d:\winddk\7600.16385.1
OBJECT_ROOT=d:\winddk\7600.16385.1
MAKEDIR_LOWERCASE=d:\kituri_programe\i2c-controller-xp\i2cctrl
OBJ_PATH=d:\kituri_programe\i2c-controller-xp\i2cctrl
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
