

386_OBJECTS=\
 $(OBJ_PATH)\$O\i2cctrl_emu.obj \
 $(OBJ_PATH)\$O\i2cctrl_emu_acpi.obj \
 $(OBJ_PATH)\$O\i2cctrl_emu_ops.obj \
 $(OBJ_PATH)\$O\i2cctrl_emu_hid.obj \
 $(OBJ_PATH)\$O\i2cctrl_emu_ioctl.obj \


_RES_FILE=$(OBJ_PATH)\$O\i2cctrl_emu_version.res



# lowercased
BASEDIR=d:\winddk\7600.16385.1
OBJECT_ROOT=d:\winddk\7600.16385.1
MAKEDIR_LOWERCASE=d:\kituri_programe\i2c-controller-xp\i2cctrl_emulator
OBJ_PATH=d:\kituri_programe\i2c-controller-xp\i2cctrl_emulator
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
