#ifndef _GPIOCTRL_PUBLIC_H_
#define _GPIOCTRL_PUBLIC_H_

#include <ntddk.h>

/* Public device name */
#define GPIOCTRL_DEVICE_NAME   L"\\Device\\GpioCtrl"
#define GPIOCTRL_SYMLINK_NAME  L"\\DosDevices\\GpioCtrl"

/* IOCTL base */
#define GPIOCTRL_DEVICE_TYPE   FILE_DEVICE_UNKNOWN
#define GPIOCTRL_IOCTL_INDEX   0x800

/* Public IOCTLs */
#define IOCTL_GPIOCTRL_READ_PIN \
    CTL_CODE(GPIOCTRL_DEVICE_TYPE, GPIOCTRL_IOCTL_INDEX + 0x01, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_GPIOCTRL_WRITE_PIN \
    CTL_CODE(GPIOCTRL_DEVICE_TYPE, GPIOCTRL_IOCTL_INDEX + 0x02, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_GPIOCTRL_CONFIGURE_PIN \
    CTL_CODE(GPIOCTRL_DEVICE_TYPE, GPIOCTRL_IOCTL_INDEX + 0x03, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_GPIOCTRL_QUERY_CAPS \
    CTL_CODE(GPIOCTRL_DEVICE_TYPE, GPIOCTRL_IOCTL_INDEX + 0x04, METHOD_BUFFERED, FILE_ANY_ACCESS)

/* Crash IOCTL (public because gpioctrl.c handles it) */
#define IOCTL_GPIOCTRL_FORCE_CRASH \
    CTL_CODE(GPIOCTRL_DEVICE_TYPE, GPIOCTRL_IOCTL_INDEX + 0x05, METHOD_BUFFERED, FILE_ANY_ACCESS)

/* NEW: interrupt wait IOCTL for i2cctrl.sys */
#define IOCTL_GPIOCTRL_WAIT_FOR_INTERRUPT \
    CTL_CODE(GPIOCTRL_DEVICE_TYPE, GPIOCTRL_IOCTL_INDEX + 0x10, METHOD_BUFFERED, FILE_ANY_ACCESS)

/* Public structures */
typedef struct _GPIOCTRL_CAPS {
    ULONG PinCount;
    ULONG SupportsPull;
    ULONG SupportsInterrupts;
    ULONG SupportsDebounce;
} GPIOCTRL_CAPS, *PGPIOCTRL_CAPS;

typedef struct _GPIOCTRL_READ_PIN {
    ULONG Pin;
} GPIOCTRL_READ_PIN, *PGPIOCTRL_READ_PIN;

typedef struct _GPIOCTRL_WRITE_PIN {
    ULONG Pin;
    ULONG Value;
} GPIOCTRL_WRITE_PIN, *PGPIOCTRL_WRITE_PIN;

typedef struct _GPIOCTRL_CONFIGURE_PIN {
    ULONG Pin;
    ULONG Direction;
    ULONG Pull;
    ULONG IntEnable;
    ULONG IntType;
    ULONG IntPol;
} GPIOCTRL_CONFIGURE_PIN, *PGPIOCTRL_CONFIGURE_PIN;

/* NEW: interrupt wait request/response */
typedef struct _GPIOCTRL_WAIT_REQUEST {
    ULONG Pin;
} GPIOCTRL_WAIT_REQUEST, *PGPIOCTRL_WAIT_REQUEST;

typedef struct _GPIOCTRL_WAIT_RESPONSE {
    ULONG Pin;
    ULONG Fired;
} GPIOCTRL_WAIT_RESPONSE, *PGPIOCTRL_WAIT_RESPONSE;

#endif /* _GPIOCTRL_PUBLIC_H_ */
