#ifndef _GPIOCTRL_PUBLIC_H_
#define _GPIOCTRL_PUBLIC_H_

#include <ntddk.h>

/* Public device name */
#define GPIOCTRL_DEVICE_NAME   L"\\Device\\GpioCtrl"
#define GPIOCTRL_SYMLINK_NAME  L"\\DosDevices\\GpioCtrl"

/* IOCTL base */
#define GPIOCTRL_DEVICE_TYPE   FILE_DEVICE_UNKNOWN
#define GPIOCTRL_IOCTL_INDEX   0x800

/* Public IOCTLs */
#define IOCTL_GPIO_READ_PIN \
    CTL_CODE(GPIOCTRL_DEVICE_TYPE, GPIOCTRL_IOCTL_INDEX + 0x01, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_GPIO_WRITE_PIN \
    CTL_CODE(GPIOCTRL_DEVICE_TYPE, GPIOCTRL_IOCTL_INDEX + 0x02, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_GPIO_CONFIGURE_PIN \
    CTL_CODE(GPIOCTRL_DEVICE_TYPE, GPIOCTRL_IOCTL_INDEX + 0x03, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_GPIO_QUERY_CAPS \
    CTL_CODE(GPIOCTRL_DEVICE_TYPE, GPIOCTRL_IOCTL_INDEX + 0x04, METHOD_BUFFERED, FILE_ANY_ACCESS)

/* Crash IOCTL (public because gpioctrl.c handles it) */
#define IOCTL_GPIO_FORCE_CRASH \
    CTL_CODE(GPIOCTRL_DEVICE_TYPE, GPIOCTRL_IOCTL_INDEX + 0x05, METHOD_BUFFERED, FILE_ANY_ACCESS)

/* NEW: interrupt wait IOCTL for i2cctrl.sys */
#define IOCTL_GPIO_WAIT_FOR_INTERRUPT \
    CTL_CODE(GPIOCTRL_DEVICE_TYPE, GPIOCTRL_IOCTL_INDEX + 0x10, METHOD_BUFFERED, FILE_ANY_ACCESS)

/* Public structures */
typedef struct _GPIOCTRL_CAPS {
    ULONG PinCount;
    ULONG SupportsPull;
    ULONG SupportsInterrupts;
    ULONG SupportsDebounce;
} GPIOCTRL_CAPS, *PGPIOCTRL_CAPS;

typedef struct _GPIO_READ_PIN {
    ULONG Pin;
} GPIO_READ_PIN, *PGPIO_READ_PIN;

typedef struct _GPIO_WRITE_PIN {
    ULONG Pin;
    ULONG Value;
} GPIO_WRITE_PIN, *PGPIO_WRITE_PIN;

typedef struct _GPIO_CONFIGURE_PIN {
    ULONG Pin;
    ULONG Direction;
    ULONG Pull;
    ULONG IntEnable;
    ULONG IntType;
    ULONG IntPol;
} GPIO_CONFIGURE_PIN, *PGPIO_CONFIGURE_PIN;

/* NEW: interrupt wait request/response */
typedef struct _GPIO_WAIT_REQUEST {
    ULONG Pin;
} GPIO_WAIT_REQUEST, *PGPIO_WAIT_REQUEST;

typedef struct _GPIO_WAIT_RESPONSE {
    ULONG Pin;
    ULONG Fired;
} GPIO_WAIT_RESPONSE, *PGPIO_WAIT_RESPONSE;

#endif /* _GPIOCTRL_PUBLIC_H_ */
