

386_OBJECTS=\
 $(OBJ_PATH)\$O\gpioctrl.obj \
 $(OBJ_PATH)\$O\gpioctrl_io.obj \
 $(OBJ_PATH)\$O\gpioctrl_isr.obj \
 $(OBJ_PATH)\$O\gpioctrl_reg.obj \


_RES_FILE=$(OBJ_PATH)\$O\gpioctrl_version.res



# lowercased
BASEDIR=d:\winddk\7600.16385.1
OBJECT_ROOT=d:\winddk\7600.16385.1
MAKEDIR_LOWERCASE=d:\kituri_programe\i2c-controller-xp\gpioctrl
OBJ_PATH=d:\kituri_programe\i2c-controller-xp\gpioctrl
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
